spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    driver-class-name: org.postgresql.Driver
    username: 'postgres'
    password: 'password'
    url: 'jdbc:postgresql://localhost:5433/travelregistry'